# For more information on this configuration file, see containers-registries.conf(5).

# NOTE: RISK://registries.search" allows pulling short names (e.g., "ubuntu")
# from these registries in order. This is convenient but may be a security risk.

unqualified-search-registries = ["docker.io", "quay.io", "ghcr.io"]

# Registries that do not use TLS when pulling images or uses self-signed certificates.
# [[registry]]
# location = "localhost:5000"
# insecure = true
