# For more information on shortnames, see containers-registries.conf(5).
[aliases]
  "alpine" = "docker.io/library/alpine"
  "busybox" = "docker.io/library/busybox"
  "centos" = "quay.io/centos/centos"
  "debian" = "docker.io/library/debian"
  "fedora" = "registry.fedoraproject.org/fedora"
  "nginx" = "docker.io/library/nginx"
  "node" = "docker.io/library/node"
  "python" = "docker.io/library/python"
  "redis" = "docker.io/library/redis"
  "ubuntu" = "docker.io/library/ubuntu"
